import React, { useState } from 'react';
import { CheckCircle, XCircle, ChevronRight, Award, RotateCcw, Download, Sparkles, Loader2 } from 'lucide-react';
import { addQuizAttempt, generateNoteQuizzes } from '../services/note';
import { motion, AnimatePresence } from 'framer-motion';
import confetti from 'canvas-confetti';

const MCQQuiz = ({ quizzes = [], noteId, onQuizzesGenerated }) => {
  const [currentQuestionIndex, setCurrentQuestionIndex] = useState(0);
  const [selectedOption, setSelectedOption] = useState(null);
  const [isAnswered, setIsAnswered] = useState(false);
  const [score, setScore] = useState(0);
  const [quizFinished, setQuizFinished] = useState(false);
  const [generating, setGenerating] = useState(false);
  const [generationError, setGenerationError] = useState('');

  const currentQuestion = quizzes[currentQuestionIndex];

  const handleOptionClick = (option) => {
    if (isAnswered) return;
    setSelectedOption(option);
    setIsAnswered(true);

    if (option === currentQuestion.correctAnswer) {
      setScore(prev => prev + 1);
    }
  };

  const handleNext = async () => {
    if (currentQuestionIndex < quizzes.length - 1) {
      setCurrentQuestionIndex(prev => prev + 1);
      setSelectedOption(null);
      setIsAnswered(false);
    } else {
      setQuizFinished(true);
      
      // Fire confetti if score is high
      const scorePercent = (score / quizzes.length) * 100;
      if (scorePercent >= 70) {
        confetti({
          particleCount: 100,
          spread: 70,
          origin: { y: 0.6 }
        });
      }

      // Save attempt to database
      if (noteId) {
        setSavingAttempt(true);
        try {
          await addQuizAttempt(noteId, score, quizzes.length);
        } catch (error) {
          console.error('Failed to save quiz attempt:', error);
        } finally {
          setSavingAttempt(false);
        }
      }
    }
  };

  const handleRestart = () => {
    setCurrentQuestionIndex(0);
    setSelectedOption(null);
    setIsAnswered(false);
    setScore(0);
    setQuizFinished(false);
  };

  const downloadQuizPDF = () => {
    const printWindow = window.open('', '_blank');
    if (!printWindow) return;

    const htmlContent = `
      <html>
      <head>
        <title>Quiz - Study AI</title>
        <style>
          body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            color: #1e293b;
            padding: 40px;
            max-width: 800px;
            margin: 0 auto;
            line-height: 1.5;
          }
          h1 {
            font-size: 24px;
            color: #4f46e5;
            border-bottom: 2px solid #e2e8f0;
            padding-bottom: 10px;
            margin-bottom: 20px;
          }
          .quiz-item {
            margin-bottom: 25px;
            page-break-inside: avoid;
          }
          .question {
            font-weight: 600;
            font-size: 16px;
            margin-bottom: 10px;
          }
          .options {
            list-style-type: none;
            padding-left: 0;
          }
          .option {
            padding: 8px 12px;
            border: 1px solid #cbd5e1;
            border-radius: 6px;
            margin-bottom: 6px;
            font-size: 14px;
          }
          .answer-key {
            margin-top: 50px;
            page-break-before: always;
            border-top: 2px dashed #cbd5e1;
            padding-top: 20px;
          }
          .answer-item {
            font-size: 14px;
            margin-bottom: 10px;
          }
        </style>
      </head>
      <body>
        <h1>Study Notes Quiz</h1>
        <p style="font-size: 14px; color: #64748b; margin-bottom: 30px;">
          Generated by AI Study Assistant. Total questions: ${quizzes.length}
        </p>
        
        ${quizzes.map((quiz, idx) => `
          <div class="quiz-item">
            <div class="question">${idx + 1}. ${quiz.question}</div>
            <ul class="options">
              ${quiz.options.map(opt => `
                <li class="option">${opt}</li>
              `).join('')}
            </ul>
          </div>
        `).join('')}

        <div class="answer-key">
          <h2>Answer Key</h2>
          ${quizzes.map((quiz, idx) => `
            <div class="answer-item">
              <strong>Question ${idx + 1}:</strong> ${quiz.correctAnswer}
            </div>
          `).join('')}
        </div>

        <script>
          window.onload = function() {
            window.print();
          };
        </script>
      </body>
      </html>
    `;

    printWindow.document.write(htmlContent);
    printWindow.document.close();
  };

  const handleGenerateQuizzes = async () => {
    setGenerating(true);
    setGenerationError('');
    try {
      const data = await generateNoteQuizzes(noteId);
      if (onQuizzesGenerated) {
        onQuizzesGenerated(data.quizzes);
      }
    } catch (err) {
      console.error(err);
      setGenerationError(err.response?.data?.message || 'Failed to generate MCQ quiz. Please try again.');
    } finally {
      setGenerating(false);
    }
  };

  if (quizzes.length === 0) {
    return (
      <div className="max-w-md mx-auto text-center py-16 px-6 bg-white dark:bg-slate-900 rounded-2xl border border-slate-200 dark:border-slate-800 shadow-sm">
        <div className="inline-flex p-4 bg-indigo-50 dark:bg-indigo-950/30 text-indigo-600 dark:text-indigo-400 rounded-3xl mb-6">
          <Sparkles size={40} className={generating ? "animate-pulse" : ""} />
        </div>
        <h3 className="text-xl font-bold mb-2 text-slate-800 dark:text-slate-100">No MCQ Quiz Yet</h3>
        <p className="text-slate-500 dark:text-slate-400 text-sm mb-8 leading-relaxed">
          Test your knowledge! We can automatically generate a custom multiple-choice quiz based on the text of your uploaded PDF.
        </p>

        {generationError && (
          <div className="mb-6 p-4 bg-red-50 dark:bg-red-950/20 border border-red-200/50 dark:border-red-800/50 rounded-xl text-red-600 dark:text-red-400 text-sm font-medium">
            {generationError}
          </div>
        )}

        <button
          onClick={handleGenerateQuizzes}
          disabled={generating}
          className="inline-flex items-center justify-center gap-2.5 w-full py-3.5 bg-indigo-600 hover:bg-indigo-700 disabled:bg-indigo-400 text-white font-semibold text-sm rounded-xl shadow-md shadow-indigo-600/10 hover:shadow-lg transition-all cursor-pointer"
        >
          {generating ? (
            <>
              <Loader2 size={16} className="animate-spin" />
              <span>Generating Quiz...</span>
            </>
          ) : (
            <>
              <Sparkles size={16} />
              <span>Generate MCQ Quiz</span>
            </>
          )}
        </button>
      </div>
    );
  }

  return (
    <div className="max-w-3xl mx-auto">
      <AnimatePresence mode="wait">
        {!quizFinished ? (
          <motion.div
            key="quiz-active"
            initial={{ opacity: 0, y: 15 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: -15 }}
            className="glass-card rounded-2xl p-6 md:p-8"
          >
            {/* Header: Progress bar */}
            <div className="flex items-center justify-between mb-6">
              <span className="text-xs font-semibold text-slate-500 dark:text-slate-400 uppercase tracking-wider">
                Question {currentQuestionIndex + 1} of {quizzes.length}
              </span>
              <span className="text-xs font-bold text-indigo-600 dark:text-indigo-400">
                Score: {score}
              </span>
            </div>

            {/* Progress line */}
            <div className="w-full h-1.5 bg-slate-100 dark:bg-slate-800 rounded-full mb-8 overflow-hidden">
              <div
                className="h-full bg-indigo-600 dark:bg-indigo-400 rounded-full transition-all duration-300"
                style={{ width: `${((currentQuestionIndex + 1) / quizzes.length) * 100}%` }}
              />
            </div>

            {/* Question Text */}
            <h3 className="text-lg md:text-xl font-bold mb-6 text-slate-800 dark:text-slate-100">
              {currentQuestion.question}
            </h3>

            {/* Options List */}
            <div className="space-y-3.5 mb-8">
              {currentQuestion.options.map((option, idx) => {
                const isSelected = selectedOption === option;
                const isCorrect = option === currentQuestion.correctAnswer;
                
                let btnStyle = 'border-slate-200 dark:border-slate-800 hover:border-slate-300 dark:hover:border-slate-700 bg-white dark:bg-slate-900';
                let icon = null;

                if (isAnswered) {
                  if (isCorrect) {
                    btnStyle = 'border-emerald-500 bg-emerald-50/20 text-emerald-800 dark:text-emerald-300 dark:bg-emerald-950/20';
                    icon = <CheckCircle size={18} className="text-emerald-500 shrink-0" />;
                  } else if (isSelected) {
                    btnStyle = 'border-red-500 bg-red-50/20 text-red-800 dark:text-red-300 dark:bg-red-950/20';
                    icon = <XCircle size={18} className="text-red-500 shrink-0" />;
                  } else {
                    btnStyle = 'border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-900 opacity-50';
                  }
                }

                return (
                  <button
                    key={idx}
                    disabled={isAnswered}
                    onClick={() => handleOptionClick(option)}
                    className={`flex items-center justify-between w-full p-4 border rounded-xl text-left font-medium transition-all duration-200 ${
                      !isAnswered && 'hover:bg-slate-50 dark:hover:bg-slate-800/50 hover:-translate-y-0.5'
                    } ${btnStyle}`}
                  >
                    <span className="text-sm md:text-base leading-snug pr-4">{option}</span>
                    {icon}
                  </button>
                );
              })}
            </div>

            {/* Bottom Actions */}
            <div className="flex justify-between items-center">
              <button
                onClick={downloadQuizPDF}
                className="flex items-center gap-2 text-xs font-semibold text-slate-500 hover:text-indigo-600 transition-colors cursor-pointer"
              >
                <Download size={14} />
                Download PDF
              </button>

              <AnimatePresence>
                {isAnswered && (
                  <motion.button
                    initial={{ opacity: 0, scale: 0.95 }}
                    animate={{ opacity: 1, scale: 1 }}
                    exit={{ opacity: 0, scale: 0.95 }}
                    onClick={handleNext}
                    className="flex items-center gap-2 bg-indigo-600 hover:bg-indigo-700 text-white font-semibold text-sm px-6 py-3 rounded-xl shadow-sm hover:shadow transition-all cursor-pointer"
                  >
                    <span>{currentQuestionIndex === quizzes.length - 1 ? 'Finish Quiz' : 'Next Question'}</span>
                    <ChevronRight size={16} />
                  </motion.button>
                )}
              </AnimatePresence>
            </div>
          </motion.div>
        ) : (
          // Quiz Completed Screen
          <motion.div
            key="quiz-finished"
            initial={{ opacity: 0, scale: 0.95 }}
            animate={{ opacity: 1, scale: 1 }}
            className="glass-card rounded-2xl p-8 text-center max-w-md mx-auto"
          >
            <div className="inline-flex p-4 bg-indigo-50 dark:bg-indigo-950/50 text-indigo-600 dark:text-indigo-400 rounded-3xl mb-6">
              <Award size={48} />
            </div>

            <h2 className="text-2xl font-bold mb-2">Quiz Completed!</h2>
            
            {/* Score display */}
            <div className="my-6">
              <p className="text-slate-500 dark:text-slate-400 text-sm mb-1">Your Score</p>
              <h3 className="text-5xl font-extrabold text-indigo-600 dark:text-indigo-400">
                {score} <span className="text-xl font-medium text-slate-400">/ {quizzes.length}</span>
              </h3>
              <p className="text-sm font-semibold mt-2 text-slate-600 dark:text-slate-300">
                {Math.round((score / quizzes.length) * 100)}% Correct
              </p>
            </div>

            <p className="text-sm text-slate-500 dark:text-slate-400 mb-8 leading-relaxed">
              {score === quizzes.length 
                ? 'Perfect score! You have mastered this study material.' 
                : score >= quizzes.length * 0.7 
                ? 'Great job! You have a solid understanding of this content.' 
                : 'Good attempt. Review the summary notes and try again to improve.'}
            </p>

            <div className="flex flex-col gap-3">
              <button
                onClick={handleRestart}
                className="flex items-center justify-center gap-2 w-full py-3 bg-indigo-600 hover:bg-indigo-700 text-white font-semibold text-sm rounded-xl shadow-sm transition-all cursor-pointer"
              >
                <RotateCcw size={16} />
                Retake Quiz
              </button>
              
              <button
                onClick={downloadQuizPDF}
                className="flex items-center justify-center gap-2 w-full py-3 bg-slate-100 hover:bg-slate-200 dark:bg-slate-800 dark:hover:bg-slate-700 text-slate-700 dark:text-slate-300 font-semibold text-sm rounded-xl transition-all cursor-pointer"
              >
                <Download size={16} />
                Download Quiz PDF
              </button>
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
};

export default MCQQuiz;
